LaClinica.Presentacion/Models/ErrorViewModel.cs
using System;

namespace LaClinica.Presentacion.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LaClinica.Presentacion/Models/LlamadaViewModel.cs
using LaClinica.Dominio.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LaClinica.Presentacion.Models
{
    public class LlamadaViewModel
    {
        public LlamadaViewModel()
        {
            Sintomas = new List<LlamadaSintoma>();
        }

        [DataType(DataType.Time)]
        public DateTime Hora { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }


        [Required(ErrorMessage = "Dato obligatorio")]
        [StringLength(8, MinimumLength = 7)]
        public int DNI { get; set; }
        [Required(ErrorMessage = "Dato obligatorio")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Dato obligatorio")]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "Dato obligatorio")]
        public int Telefono { get; set; }
        [Required(ErrorMessage = "Dato obligatorio")]
        public string Domicilio { get; set; }
        [DataType(DataType.Date)]
        public DateTime FechaNacimiento { get; set; }

        [Required(ErrorMessage = "Dato obligatorio")]
        public EstadoLlamada Estado { get; set; }

        public ICollection<LlamadaSintoma> Sintomas { get; set; }
        [Required(ErrorMessage = "Dato obligatorio")]
        public Recurso Recurso { get; set; }
        [Required(ErrorMessage = "Dato obligatorio")]
        public Operador Operador { get; set; }

    }
}

LaClinica.Presentacion/Models/PersonaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LaClinica.Presentacion.Models
{
    public class PersonaViewModel
    {
        

    }
}

LaClinica.Presentacion/Controllers/HomeController.cs
using LaClinica.Presentacion.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LaClinica.Presentacion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LaClinica.Presentacion/Controllers/Llamadas/LlamadasController.cs
using LaClinica.Dominio;
using LaClinica.Dominio.Contratos;
using LaClinica.Presentacion.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace LaClinica.Presentacion.Controllers.Llamadas
{
    public class LlamadasController : Controller
    {
        private readonly IRepositorioSintomas repositorioSintomas;
        private readonly IRepositorioLlamadas repositorioLlamadas;

        public LlamadasController(IRepositorioSintomas repositorioSintomas, IRepositorioLlamadas repositorioLlamadas)
        {
            this.repositorioSintomas = repositorioSintomas;
            this.repositorioLlamadas = repositorioLlamadas;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            ViewBag.hora = DateTime.Now.ToString("HH:mm");
            return View();
        }

        [HttpPost]
        public IActionResult Post(LlamadaViewModel Llamada)
        {
            List<LlamadaViewModel> Llamadas = new List<LlamadaViewModel>();
            var listaLlamada = repositorioLlamadas.GetLlamada();

            foreach (Llamada llam in listaLlamada)
            {
                Llamadas()
            }

            repositorioLlamadas.CreateLlamada(Llamada);

            ViewBag.hora = DateTime.Now.ToString("HH:mm");
            return View();
        }

    }
}

LaClinica.Presentacion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LaClinica.Presentacion/Views/Llamadas/Create.cshtml
@model LaClinica.Presentacion.Models.LlamadaViewModel

@{
    var fecha = DateTime.Now.ToString("dd/MM/yyyy");
    var hora = ViewBag.hora;
}

<div class="row">
    <div class= "col-auto"> 
        <form asp-controller="Llamadas" asp-action= "Create"> </form>
        <div class= "form-group"> 
            <label class="control-label"> DNI </label>                 
            <input class="form-control" /> 
        </div>
        <div class= "form-group"> 
            <label class="control-label"> Nombre </label>                 
            <input class="form-control" /> 
        </div>
        <div class="form-group">                 
            <label class="control-label"> Apellido </label>                 
            <input class="form-control" /> 
        </div>
    </div>
    <div class= "col-auto">
        <div class="form-group">             
        <label class="control-label" id="fecha">@fecha</label>   
        </div>
        <div class="form-group">             
        <label class="control-label">@hora</label>                 
        </div>
    </div>
</div>

<hr/>

LaClinica.Presentacion/Views/Llamadas/Index.cshtml
@{
}

LaClinica.Presentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaClinica.Presentacion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LaClinica.Presentacion</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Llamadas" asp-action="Create">Llamadas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LaClinica.Presentacion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>